### ISSUE TITLE
'Waiting for user input' turned off - still QRs under this are active while conversing with the bot

### ISSUE THREAD

**Issue by ashu2390** [scupid-admin/Morph.ai-Support#104]
Brand ID: healthcarefn1br

**Comment by deemorph** [comment]
@ashu2390  which conversation?

**Comment by deemorph** [comment]
@vidzi
Sorry forgot to tell you and update the issue, Ashutosh had already told me about this. This issue occurs for every conversation. The issue is: if a user first creates a node with "wait for user input" & adds some QR and later on updates the same by unsetting "wait for user input", the QR remains saved in the BotSays message and while sending message we are not doing any specific check if QR's exists or not in the message.

To solve this either we'll have to add a check in backend for this or the node needs to be updated with empty suggestions when "wait for user input" is turned off. Can you tell me which approach should we move forward with.

**Comment by deemorph** [comment]
@vidzi 
PR for fix: https://github.com/scupid-admin/morph/pull/728

**Comment by deemorph** [comment]
@vidzi 
Can i merge the PR?

**Comment by deemorph** [comment]
Fixed. Changes deployed on production.
