### ISSUE TITLE
Only one webservice result is coming.

### ISSUE THREAD

**Issue by inuishan** [scupid-admin/Morph.ai-Support#35]

**Comment by Deepak54321** [comment]
DealerDetailsApi(Conversation Name)
package com.altin.custom_code;

import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation.Builder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;

import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.client.ClientProperties;
import org.glassfish.jersey.jackson.JacksonFeature;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.util.JSONPObject;

import jersey.repackaged.com.google.common.collect.Lists;
import morph.base.actions.Action;
import morph.base.actions.StringVariable;
import morph.base.actions.VariableScope;
import morph.base.actions.impl.PublishMessageAction;
import morph.base.actions.impl.SetVariableAction;
import morph.base.beans.CustomCodeResponse;
import morph.base.beans.simplifiedmessage.TextMessagePayload;

/**
 * @author ishanjain
 * @since 18/07/17
 */

public class MorphCustomCode implements RequestHandler<Map<String, Object>, CustomCodeResponse> {

	/*public class CustomJsonResponse {
		public ResponseDataClass responseData;
	}

	public class ResponseDataClass {
		public Dealer[] dealers;
	}

	public class Dealer {
		public String dealer_id;
	}*/

	@Override
	public CustomCodeResponse handleRequest(Map<String, Object> input, Context context) {

		// Write your code here
		Client client = ClientBuilder.newBuilder()
				.withConfig(new ClientConfig().property(ClientProperties.SUPPRESS_HTTP_COMPLIANCE_VALIDATION, true))
				.register(JacksonFeature.class).build();
				
 Map<String, Object> userVariables = (Map<String, Object>) input.get("userVariables");
        
        String State = (String) userVariables.get("Customer State").trim();
        
        String City=(String) userVariables.get("Customers city").trim();
        

		WebTarget target = client.target(
				"http://www.yamaha-motor-india.com/iym-web-api//51DCDFC2A2BC9/network/search?type=sales&profile_id=gujarat&city_profile_id=ahmedabad");
		Builder request = target.request();
		Response response = request.get();
		String responseStr = response.readEntity(String.class);

		ObjectMapper objMapper = new ObjectMapper();

		// CustomJsonResponse data = objMapper.readValue(responseStr,
		// CustomJsonResponse.class);

		CustomCodeResponse customCodeResponse = new CustomCodeResponse();
		try {

			JsonNode rootNode = objMapper.readTree(responseStr);

			JsonNode responseData = rootNode.get("responseData");

			Iterator<JsonNode> dealerNodes = responseData.get("dealers").elements();

			List<Action> actions = Lists.newArrayList();
			
			JsonNode dealer;

			String result = "";
			
			String newLine = "\n";

			while (dealerNodes.hasNext()) {
				
				dealer = dealerNodes.next();
				
				result += "Dealer Code: " + dealer.get("dealer_code").asText() + newLine +
						"Dealer Name: " + dealer.get("dealer_name").asText() + newLine +
						"Address: " + dealer.get("dealer_address").asText() + newLine +
						"Service Address: " + dealer.get("dealer_service_address").asText() + newLine +
						"------------" + newLine;
			}
			
			actions.add(
					new SetVariableAction("StatusIdlist", VariableScope.USER, new StringVariable().value(State.trim())));
			actions.add(
					new SetVariableAction("StateNameList", VariableScope.USER, new StringVariable().value(City.trim())));
			actions.add(
					new SetVariableAction("ProfileIdList", VariableScope.USER, new StringVariable().value(result)));

			customCodeResponse.setActions(actions);

		} catch (Exception e) {
			e.printStackTrace();

		}
		return customCodeResponse;
	}

}

**Comment by Deepak54321** [comment]
Copy_Of_DealerDetails_ApI(Conversation Name)
package com.altin.custom_code;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation.Builder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;

import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.client.ClientProperties;
import org.glassfish.jersey.jackson.JacksonFeature;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import jersey.repackaged.com.google.common.collect.Lists;
import morph.base.actions.Action;
import morph.base.actions.StringVariable;
import morph.base.actions.VariableScope;

import morph.base.actions.impl.SetVariableAction;
import morph.base.beans.CustomCodeResponse;

public class MorphCustomCode implements RequestHandler<Map<String, Object>, CustomCodeResponse> {

	@Override
	public CustomCodeResponse handleRequest(Map<String, Object> input, Context context) {

		// Write your code here
		Client client = ClientBuilder.newBuilder()
				.withConfig(new ClientConfig().property(ClientProperties.SUPPRESS_HTTP_COMPLIANCE_VALIDATION, true))
				.register(JacksonFeature.class).build();

		WebTarget target = client.target(
				"http://www.yamaha-motor-india.com/iym-web-api//51DCDFC2A2BC9/statewiseprice/getprice?product_profile_id=salutorxspcol&state_id=240");
		Builder request = target.request();
		Response response = request.get();
		String responseStr = response.readEntity(String.class);

		ObjectMapper objMapper = new ObjectMapper();

		CustomCodeResponse customCodeResponse = new CustomCodeResponse();
		try {

			JsonNode rootNode = objMapper.readTree(responseStr);

			JsonNode responseData = rootNode.get("responseData");

			Iterator<JsonNode> dealerNodes = responseData.get("product_price").elements();

			String price = "";

			if (dealerNodes.hasNext()) {
				price = dealerNodes.next().get("price").asText();
			}

			List<Action> actions = Lists.newArrayList();
			actions.add(new SetVariableAction("ProductPrice", VariableScope.USER, new StringVariable().value(price)));

			customCodeResponse.setActions(actions);

		} catch (Exception e) {
			e.printStackTrace();

		}
		return customCodeResponse;
	}

}

**Comment by Deepak54321** [comment]
Both of them working correctly when there one conversation using web service.

**Comment by inuishan** [comment]
@Deepak54321 Can you please also attach screenshots?

**Comment by Deepak54321** [comment]
![image](https://user-images.githubusercontent.com/31242754/29740284-92c7c358-8a70-11e7-8b24-b5d0de319b95.png)

**Comment by Deepak54321** [comment]
![image](https://user-images.githubusercontent.com/31242754/29740321-4f66f5b0-8a71-11e7-80d7-e6a764d886ef.png)

**Comment by inuishan** [comment]
Increased the memory allocated to the function
